#!/bin/sh
while read file
do
        case "$1" in
        "C-d")
                mv "$file" ~/.trash ;;
        "C-c")
                sudo ~/dev/dotfiles/bin/cliper "$file" ;;
        "C-w")
                wal -i "$file" ;;
        esac
done
